#!/bin/bash
set -e

mvn clean package

if [ $ENV = "dev" ] ; then
  echo "========= Run Development ========="
  docker compose -f docker-compose.dev.yml up -d --build
elif [ $ENV = "prod" ] ; then
  echo "========= Run Production ========="
  docker compose -f docker-compose.prod.yml up -d --build
else
  echo "========= Run Local ========="
  docker compose up -d --build
fi